"""add indicator status table and remove status from basic indicator table 

Revision ID: 5c6f0c6416cf
Revises: cfc8bad1fbca
Create Date: 2025-07-04 19:00:52.709156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c6f0c6416cf'
down_revision: Union[str, Sequence[str], None] = 'cfc8bad1fbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicator_statuses_id'), table_name='indicator_statuses')
    op.drop_table('indicator_statuses')
    op.drop_index(op.f('ix_analysis_id'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_column('indicators', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('output_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_pkey'))
    )
    op.create_index(op.f('ix_analysis_id'), 'analysis', ['id'], unique=False)
    op.create_table('indicator_statuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('indicator_statuses_pkey'))
    )
    op.create_index(op.f('ix_indicator_statuses_id'), 'indicator_statuses', ['id'], unique=False)
    # ### end Alembic commands ###
