"""Added analysis table

Revision ID: a7bf37ee2ee7
Revises: c7528a307651
Create Date: 2025-07-03 16:59:33.968495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7bf37ee2ee7'
down_revision: Union[str, Sequence[str], None] = 'c7528a307651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regulation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indicator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('indicator_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alignment_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], name=op.f('analysis_results_regulation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_results_pkey'))
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    # ### end Alembic commands ###
